name: Jules Boussekeyt - WebDev Blog
description: A blog about Javascript, PHP, webdesign and above all web applications in general.
url: http://jules.boussekeyt.org
google_analytics: UA-19244753-1
disqus_username: grdn

safe: true
permalink: /:year/:title.html
pygments: true
markdown: redcarpet
include: ['examples', 'game-of-life']
