name: Jules Boussekeyt - WebDev Blog
description: A blog about Javascript, PHP, webdesign and above all web applications in general.
url: http://jules.boussekeyt.org

safe: true
permalink: /:year/:title.html
pygments: true
markdown: redcarpet
